const en = {
  errors: {
    setupDone: "Initial setup already completed",
    registrationDisabled: "Registrations are disabled",
    emailTaken: "Email already in use",
    invalidCredentials: "Invalid credentials",
    tooManyAttempts: "Too many attempts — try again in a minute.",
    invalidPassword: "Incorrect password",
    accountDisabled: "Account disabled",
    dbAlreadyConfigured: "Database already configured",
    invalidDbUrl: "Invalid PostgreSQL URL (expected: postgresql://user:pass@host:5432/db)",
    userNotFound: "User not found",
    cannotDeleteSelf: "You cannot delete yourself",
    proxyNotFound: "Proxy account not found",
    proxyNotAssigned: "This proxy is not assigned to you",
    portReserved: "This port is reserved for the default proxy port",
    portTaken: "This port is already used by another pool or proxy account",
    portOutOfRange: "The port must be within the published range (default 9000-9250)",
    sourceNotFound: "Source not found",
    tokenMissing: "Missing token",
    tokenInvalid: "Invalid or expired token",
    accountMissing: "Account missing or disabled",
    forbiddenRole: "Access restricted",
    apiKeyMissing: "API key not configured",
    apiKeyInvalid: "Invalid API key",
    adminOnly: "Administrators only",
    tokenRequired: "Missing token",
    captchaFailed: "Captcha verification failed",
    addonNotFound: "Addon not found",
    restore: {
      dbNotConfigured: "Configure the database first.",
      locked: "Installation already completed — restoring is no longer available.",
      busy: "A restore is already in progress.",
      badSize: "Invalid file size.",
      tooLarge: "Archive too large.",
      noSpace: "Not enough free disk space for the restore",
      unknownUpload: "Unknown or expired upload — start again.",
      badOffset: "Upload out of sync — resuming.",
      badChunk: "Invalid upload chunk.",
      uploadFailed: "Upload interrupted.",
      incomplete: "Upload incomplete.",
      notArchive: "This file is not a valid .tar.gz archive.",
      notPgdata: "This archive does not contain a PostgreSQL data directory (PG_VERSION not found).",
      badVersion: "Unsupported PostgreSQL version (PostgreSQL 16 required)",
      noPostgres: "PostgreSQL tools are missing from this image.",
      pgStartFailed: "The backup's database could not be started",
      pgStartTimeout: "Recovery of the backup took too long.",
      noPanelData: "No UHQ Panel OS data found in this backup.",
      restoreFailed: "Restore failed (nothing was changed)",
      failed: "Restore failed"
    }
  },
  info: {
    emailRequired: "Email address required.",
    smtpTestSent: "Test email sent.",
    smtpTestFailed: "Failed — check your SMTP settings.",
    webhookTestSent: "Test message sent.",
    webhookNotConfigured: "No webhook URL configured for this service.",
    webhookTestFailed: "Failed to send webhook"
  }
} as const;

export default en;
