const fr = {
  errors: {
    setupDone: "Configuration initiale déjà effectuée",
    registrationDisabled: "Les inscriptions sont désactivées",
    emailTaken: "Email déjà utilisé",
    invalidCredentials: "Identifiants invalides",
    tooManyAttempts: "Trop de tentatives — réessayez dans une minute.",
    invalidPassword: "Mot de passe incorrect",
    accountDisabled: "Compte désactivé",
    dbAlreadyConfigured: "Base déjà configurée",
    invalidDbUrl: "URL PostgreSQL invalide (format attendu : postgresql://user:pass@host:5432/db)",
    userNotFound: "Utilisateur introuvable",
    cannotDeleteSelf: "Impossible de se supprimer soi-même",
    proxyNotFound: "Compte proxy introuvable",
    proxyNotAssigned: "Ce proxy ne vous est pas assigné",
    portReserved: "Ce port est réservé au port proxy par défaut",
    portTaken: "Ce port est déjà utilisé par une autre pool ou un autre compte proxy",
    portOutOfRange: "Le port doit être compris dans la plage publiée (par défaut 9000-9250)",
    sourceNotFound: "Source introuvable",
    tokenMissing: "Token manquant",
    tokenInvalid: "Token invalide ou expiré",
    accountMissing: "Compte introuvable ou désactivé",
    forbiddenRole: "Accès réservé",
    apiKeyMissing: "Clé API non configurée",
    apiKeyInvalid: "Clé API invalide",
    adminOnly: "Accès réservé aux administrateurs",
    tokenRequired: "Token manquant",
    captchaFailed: "Vérification captcha échouée",
    addonNotFound: "Addon introuvable",
    restore: {
      dbNotConfigured: "Configurez d'abord la base de données.",
      locked: "Installation déjà terminée — la restauration n'est plus disponible.",
      busy: "Une restauration est déjà en cours.",
      badSize: "Taille de fichier invalide.",
      tooLarge: "Archive trop volumineuse.",
      noSpace: "Espace disque insuffisant pour la restauration",
      unknownUpload: "Envoi inconnu ou expiré — recommencez.",
      badOffset: "Envoi désynchronisé — reprise.",
      badChunk: "Morceau d'envoi invalide.",
      uploadFailed: "Envoi interrompu.",
      incomplete: "Envoi incomplet.",
      notArchive: "Ce fichier n'est pas une archive .tar.gz valide.",
      notPgdata: "Cette archive ne contient pas un dossier de données PostgreSQL (PG_VERSION introuvable).",
      badVersion: "Version de PostgreSQL non prise en charge (PostgreSQL 16 requis)",
      noPostgres: "Les outils PostgreSQL sont absents de cette image.",
      pgStartFailed: "La base de la sauvegarde n'a pas pu démarrer",
      pgStartTimeout: "La récupération de la sauvegarde a pris trop de temps.",
      noPanelData: "Aucune donnée UHQ Panel OS trouvée dans cette sauvegarde.",
      restoreFailed: "Restauration échouée (rien n'a été modifié)",
      failed: "Restauration échouée"
    }
  },
  info: {
    emailRequired: "Adresse e-mail requise.",
    smtpTestSent: "E-mail de test envoyé.",
    smtpTestFailed: "Échec — vérifiez la configuration SMTP.",
    webhookTestSent: "Message de test envoyé.",
    webhookNotConfigured: "Aucune URL de webhook configurée pour ce service.",
    webhookTestFailed: "Échec de l'envoi du webhook"
  }
} as const;

export default fr;
